name: CI
on: [push]
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - run: yarn
      - run: yarn build
      - run: yarn test
  publish:
    name: Publish
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
    - name: Install
      run: yarn install --frozen-lockfile
    - name: Build
      run: yarn build
    - uses: "phips28/gh-action-bump-version@master"
      with:
        tag-prefix: ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: NPM Publish
      run: |
        - npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
    - name: GPR Publish
      run: |
        - "echo "//npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}" >> .npmrc"
        - npm publish
      env:
        NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}:
